server:
  port: 8082

spring:
  application:
    name: logiflow-service

  datasource:
    url: jdbc:postgresql://ep-dry-silence-aoa09kmu.c-2.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: ${NEON_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 900000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

app:
  auth:
    jwt:
      issuer: tenantcore-core-service
      secret: ${APP_JWT_SECRET:tenantcore-dev-secret-change-me-tenantcore-dev-secret}
  reconciliation:
    policy:
      enforce-driver-assignment: true
      max-cod-age-hours: 72
