server:
  port: 8081

spring:
  application:
    name: core-service

  datasource:
    url: jdbc:postgresql://localhost:5432/tenant_platform_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true